version: '2'

services:
  client:
    container_name: client
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    image: hrm_client:latest
    command: ng serve --host 0.0.0.0
    volumes:
      - '.:/app'
      - '.:/app/node_modules'
    ports:
      - "4200:4200"

  server:
    container_name: server
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    image: hrm_server:latest
    command: ./server/start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"